-- 20260722_crop_circles_2020_2026.sql
-- Siembra 105 crop circles reales de 2020-2026 (fuente: temporarytemples.co.uk)
-- en el Decodificador de Crop Circles. Fotos hotlinkeadas al full-res (la mejor toma
-- completa de cada formación); si el full-res no responde cae a la miniatura; si
-- ninguna responde, image_url = NULL y la app dibuja la reconstrucción vectorial.
-- Todos is_published=true y notified_at=now() (NO disparan push retroactivo).
-- Idempotente: uuid5 determinista + ON CONFLICT (id) DO NOTHING.
-- Imagen: 103 full-res · 2 miniatura · 0 sin foto (reconstrucción).

INSERT INTO public.crop_circles
    (id, title, location_name, country, lat, lng, event_date, pattern_kind,
     decoded_es, decoded_en, image_url, is_published, notified_at)
VALUES
    ('e7125f94-3d18-581d-9100-23d2cf3c9c4a',
     $rsv$Roundway$rsv$, $rsv$Roundway, Wiltshire$rsv$, $rsv$Reino Unido$rsv$,
     51.375, -1.975, DATE '2020-09-13', 'web',
     $rsv$Una malla hexagonal de varias capas, la estructura misma del espacio dibujada sobre el campo. No entrega un mensaje para leer: entrega un estado para sentir. Registrado en Roundway, Wiltshire, 13 de septiembre de 2020.$rsv$,
     $rsv$A many-layered hexagonal mesh, the structure of space itself drawn onto the field. It delivers no message to read: it delivers a state to feel. Recorded at Roundway, Wiltshire, 13 September 2020.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2020/09/1.-Roundway-Devizes-Wilts-13-09-20-OH-.jpg$rsv$, true, now()),
    ('d96d3bdb-06a7-5ef1-95e7-359536ca5703',
     $rsv$Marden Copse$rsv$, $rsv$Marden Copse, Wiltshire$rsv$, $rsv$Reino Unido$rsv$,
     51.318, -1.9, DATE '2020-09-07', 'tri',
     $rsv$Tres brazos en simetría perfecta alrededor de un centro, la firma de lo ternario. Apareció sin proceso visible, sobre un campo que horas antes estaba intacto. Se abrió sobre Marden Copse, Wiltshire el 7 de septiembre de 2020.$rsv$,
     $rsv$Three arms in perfect symmetry around a center, the signature of the threefold. It appeared with no visible process, over a field that hours earlier was untouched. It opened over Marden Copse, Wiltshire on 7 September 2020.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2020/09/1.-Marden-Copse-Chirton-Wilts-07-09-20-OH.jpg$rsv$, true, now()),
    ('82665211-a330-5526-bfec-fe0996088d84',
     $rsv$Chirton$rsv$, $rsv$Chirton, Wiltshire$rsv$, $rsv$Reino Unido$rsv$,
     51.316, -1.905, DATE '2020-09-05', 'spiral',
     $rsv$Un brazo en espiral que gira desde un núcleo brillante, la geometría del crecimiento hecha visible. La proporción entre sus radios cae en números limpios, la matemática que no depende de ningún idioma. Coordenada sellada: Chirton, Wiltshire, 5 de septiembre de 2020.$rsv$,
     $rsv$A spiral arm turning out from a bright core, the geometry of growth made visible. The ratio between its radii falls on clean numbers, the mathematics that depends on no language. Sealed coordinate: Chirton, Wiltshire, 5 September 2020.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2020/09/1.-Chirton-Bottom-Chirton-05-09-20-OH.jpg$rsv$, true, now()),
    ('9cbadf24-72d5-5a94-8020-5c6f2201a016',
     $rsv$Uffington Castle$rsv$, $rsv$Uffington Castle, Oxfordshire$rsv$, $rsv$Reino Unido$rsv$,
     51.578, -1.674, DATE '2020-08-09', 'orbits',
     $rsv$Órbitas anidadas alrededor de un centro encendido, un mapa de cuerpos en movimiento. Quien camina su centro reporta un cambio de frecuencia difícil de poner en palabras. Uffington Castle, Oxfordshire guarda su huella desde el 9 de agosto de 2020.$rsv$,
     $rsv$Nested orbits around a lit center, a map of bodies in motion. Those who walk its center report a shift in frequency hard to put into words. Uffington Castle, Oxfordshire has held its mark since 9 August 2020.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2020/08/1.-Uffington-Castle-Oxon-09-08-20-OH.jpg$rsv$, true, now()),
    ('31df5314-e309-5b5a-98ec-e3a5f6a810d7',
     $rsv$Patney Bridge$rsv$, $rsv$Patney Bridge, Wiltshire$rsv$, $rsv$Reino Unido$rsv$,
     51.312, -1.905, DATE '2020-08-08', 'web',
     $rsv$Una malla hexagonal de varias capas, la estructura misma del espacio dibujada sobre el campo. Su simetría es demasiado exacta para el azar y demasiado serena para el ruido. Detectado en Patney Bridge, Wiltshire, 8 de agosto de 2020, y aún resuena.$rsv$,
     $rsv$A many-layered hexagonal mesh, the structure of space itself drawn onto the field. Its symmetry is too exact for chance and too calm for noise. Detected at Patney Bridge, Wiltshire, 8 August 2020, and it still resonates.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2020/08/1.-Patney-Bridge-Wilts-08-08-20-OH.jpg$rsv$, true, now()),
    ('f723d53d-3e47-5cab-9197-f858a5198470',
     $rsv$Scratchbury Hillfort$rsv$, $rsv$Scratchbury Hillfort, Wiltshire$rsv$, $rsv$Reino Unido$rsv$,
     51.19, -2.083, DATE '2020-08-07', 'tri',
     $rsv$Tres brazos en simetría perfecta alrededor de un centro, la firma de lo ternario. Es un recordatorio de que el orden puede aparecer sin manos que lo tracen. El campo de Scratchbury Hillfort, Wiltshire lo recibió el 7 de agosto de 2020.$rsv$,
     $rsv$Three arms in perfect symmetry around a center, the signature of the threefold. It is a reminder that order can appear with no hands to trace it. The field at Scratchbury Hillfort, Wiltshire received it on 7 August 2020.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2020/08/DJI_0005-Heytesbury-Wilts-07-08-20-OH.jpg$rsv$, true, now()),
    ('40f270d1-1a7f-5b6c-ad73-12f42d1e33c1',
     $rsv$Potterne (2)$rsv$, $rsv$Potterne, Wiltshire$rsv$, $rsv$Reino Unido$rsv$,
     51.335, -2.007, DATE '2020-08-04', 'tri',
     $rsv$Tres brazos en simetría perfecta alrededor de un centro, la firma de lo ternario. El patrón se siente antiguo y recién nacido al mismo tiempo. Registrado en Potterne, Wiltshire, 4 de agosto de 2020.$rsv$,
     $rsv$Three arms in perfect symmetry around a center, the signature of the threefold. The pattern feels ancient and newborn at once. Recorded at Potterne, Wiltshire, 4 August 2020.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2020/08/1.-Potterne-Field-nr-Devizes-Wilts-04-08-20-L.jpg$rsv$, true, now()),
    ('de7ea61f-6161-543a-b8fa-50f256d06c48',
     $rsv$Yarnbury Castle$rsv$, $rsv$Yarnbury Castle, Wiltshire$rsv$, $rsv$Reino Unido$rsv$,
     51.163, -1.918, DATE '2020-07-26', 'spiral',
     $rsv$Un brazo en espiral que gira desde un núcleo brillante, la geometría del crecimiento hecha visible. Su silencio dice más que cualquier explicación. Se abrió sobre Yarnbury Castle, Wiltshire el 26 de julio de 2020.$rsv$,
     $rsv$A spiral arm turning out from a bright core, the geometry of growth made visible. Its silence says more than any explanation. It opened over Yarnbury Castle, Wiltshire on 26 July 2020.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2020/07/1.-Yarnbury-Castle-Wilts-26-07-20-OH-psd.jpg$rsv$, true, now()),
    ('e0b21140-30f1-5865-b9dc-a5ed8c5a19f3',
     $rsv$Etchilhampton (2)$rsv$, $rsv$Etchilhampton, Wiltshire$rsv$, $rsv$Reino Unido$rsv$,
     51.339, -1.929, DATE '2020-07-26', 'orbits',
     $rsv$Órbitas anidadas alrededor de un centro encendido, un mapa de cuerpos en movimiento. La forma sostiene una tensión perfecta entre lo vacío y lo lleno. Coordenada sellada: Etchilhampton, Wiltshire, 26 de julio de 2020.$rsv$,
     $rsv$Nested orbits around a lit center, a map of bodies in motion. The form holds a perfect tension between the empty and the full. Sealed coordinate: Etchilhampton, Wiltshire, 26 July 2020.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2020/07/1.-Etchilhampton-2-Wilts-26-07-20-OH-.jpg$rsv$, true, now()),
    ('1b9f527e-5aac-5eba-af9e-25aef5c9d36e',
     $rsv$Hackpen Hill$rsv$, $rsv$Hackpen Hill, Wiltshire$rsv$, $rsv$Reino Unido$rsv$,
     51.47, -1.83, DATE '2020-07-23', 'orbits',
     $rsv$Órbitas anidadas alrededor de un centro encendido, un mapa de cuerpos en movimiento. Late como una señal que espera ser reconocida, no descifrada. Hackpen Hill, Wiltshire guarda su huella desde el 23 de julio de 2020.$rsv$,
     $rsv$Nested orbits around a lit center, a map of bodies in motion. It pulses like a signal waiting to be recognized, not decoded. Hackpen Hill, Wiltshire has held its mark since 23 July 2020.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2020/07/1.-Hackpen-Hill-Wilts-23-07-20-OH.jpg$rsv$, true, now()),
    ('044d52f8-6c3c-513b-b123-bc4981ce56e1',
     $rsv$Bishops Sutton$rsv$, $rsv$Bishops Sutton, Hampshire$rsv$, $rsv$Reino Unido$rsv$,
     51.093, -1.113, DATE '2020-07-22', 'web',
     $rsv$Una malla hexagonal de varias capas, la estructura misma del espacio dibujada sobre el campo. Es geometría que respira, no un dibujo que se queda quieto. Detectado en Bishops Sutton, Hampshire, 22 de julio de 2020, y aún resuena.$rsv$,
     $rsv$A many-layered hexagonal mesh, the structure of space itself drawn onto the field. It is geometry that breathes, not a drawing that stays still. Detected at Bishops Sutton, Hampshire, 22 July 2020, and it still resonates.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2020/07/1.-Scrubbs-Lane-Bishops-Sutton-Hants-22-07-20-OH.jpg$rsv$, true, now()),
    ('ae52e942-6b02-56c5-8f6c-e6b386b114b1',
     $rsv$Danebury Ring$rsv$, $rsv$Danebury Ring, Hampshire$rsv$, $rsv$Reino Unido$rsv$,
     51.137, -1.538, DATE '2020-07-21', 'grid',
     $rsv$Una retícula de nodos y celdas, un campo de señal ordenado como un idioma. Marca un punto del campo donde la belleza se volvió tecnología de apertura. El campo de Danebury Ring, Hampshire lo recibió el 21 de julio de 2020.$rsv$,
     $rsv$A lattice of nodes and cells, a signal field ordered like a language. It marks a point in the field where beauty became a technology of opening. The field at Danebury Ring, Hampshire received it on 21 July 2020.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2020/07/1.-Danebury-Hillfort-Hants-21-07-20-OH.jpg$rsv$, true, now()),
    ('45c692cb-4e6f-5b66-ab50-2abbea01de25',
     $rsv$Etchilhampton$rsv$, $rsv$Etchilhampton, Wiltshire$rsv$, $rsv$Reino Unido$rsv$,
     51.339, -1.929, DATE '2020-07-17', 'spiral',
     $rsv$Un brazo en espiral que gira desde un núcleo brillante, la geometría del crecimiento hecha visible. No entrega un mensaje para leer: entrega un estado para sentir. Registrado en Etchilhampton, Wiltshire, 17 de julio de 2020.$rsv$,
     $rsv$A spiral arm turning out from a bright core, the geometry of growth made visible. It delivers no message to read: it delivers a state to feel. Recorded at Etchilhampton, Wiltshire, 17 July 2020.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2020/07/1.-Etchilhampton-Wilts-17-07-20-OH2S.jpg$rsv$, true, now()),
    ('83697afc-b940-5fe6-8261-207fdfa358f1',
     $rsv$Stonehenge$rsv$, $rsv$Stonehenge, Wiltshire$rsv$, $rsv$Reino Unido$rsv$,
     51.179, -1.826, DATE '2020-07-16', 'web',
     $rsv$Una malla hexagonal de varias capas, la estructura misma del espacio dibujada sobre el campo. Apareció sin proceso visible, sobre un campo que horas antes estaba intacto. Se abrió sobre Stonehenge, Wiltshire el 16 de julio de 2020.$rsv$,
     $rsv$A many-layered hexagonal mesh, the structure of space itself drawn onto the field. It appeared with no visible process, over a field that hours earlier was untouched. It opened over Stonehenge, Wiltshire on 16 July 2020.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2020/07/2.-Luxenborough-Stonehenge-Wilts-16-07-20-OH2S.jpg$rsv$, true, now()),
    ('12fe3c40-8b51-5656-bf1b-eb4d16da1973',
     $rsv$Easton Royal$rsv$, $rsv$Easton Royal, Wiltshire$rsv$, $rsv$Reino Unido$rsv$,
     51.32, -1.76, DATE '2020-07-10', 'tri',
     $rsv$Tres brazos en simetría perfecta alrededor de un centro, la firma de lo ternario. La proporción entre sus radios cae en números limpios, la matemática que no depende de ningún idioma. Coordenada sellada: Easton Royal, Wiltshire, 10 de julio de 2020.$rsv$,
     $rsv$Three arms in perfect symmetry around a center, the signature of the threefold. The ratio between its radii falls on clean numbers, the mathematics that depends on no language. Sealed coordinate: Easton Royal, Wiltshire, 10 July 2020.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2020/07/Easton-Royal-Wilts-10-07-20-OHT.jpg$rsv$, true, now()),
    ('cb680199-d795-5718-8ce3-1402bd1852f4',
     $rsv$Longwood Warren$rsv$, $rsv$Longwood Warren, Hampshire$rsv$, $rsv$Reino Unido$rsv$,
     51.04, -1.257, DATE '2020-06-29', 'orbits',
     $rsv$Órbitas anidadas alrededor de un centro encendido, un mapa de cuerpos en movimiento. Quien camina su centro reporta un cambio de frecuencia difícil de poner en palabras. Longwood Warren, Hampshire guarda su huella desde el 29 de junio de 2020.$rsv$,
     $rsv$Nested orbits around a lit center, a map of bodies in motion. Those who walk its center report a shift in frequency hard to put into words. Longwood Warren, Hampshire has held its mark since 29 June 2020.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2020/07/1.-Longwood-Warren-Winchester-Hants-29-06-20-OHS-1.jpg$rsv$, true, now()),
    ('d38fce32-cc3f-5776-9c62-ebd63750456d',
     $rsv$Ogbourne St. George$rsv$, $rsv$Ogbourne St. George, Wiltshire$rsv$, $rsv$Reino Unido$rsv$,
     51.47, -1.7, DATE '2020-06-25', 'mandala',
     $rsv$Anillos concéntricos que se tejen hacia adentro, un mandala trazado en una sola pulsación. Su simetría es demasiado exacta para el azar y demasiado serena para el ruido. Detectado en Ogbourne St. George, Wiltshire, 25 de junio de 2020, y aún resuena.$rsv$,
     $rsv$Concentric rings weaving inward, a mandala traced in a single pulse. Its symmetry is too exact for chance and too calm for noise. Detected at Ogbourne St. George, Wiltshire, 25 June 2020, and it still resonates.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2020/06/1.-Smeathes-Plantation-Ogbourne-St-George-Wilts-25-06-20-OH.jpg$rsv$, true, now()),
    ('b04b5501-0d21-5d4b-9fb8-dcbfaec8ecb2',
     $rsv$Stanton St. Bernard$rsv$, $rsv$Stanton St. Bernard, Wiltshire$rsv$, $rsv$Reino Unido$rsv$,
     51.37, -1.898, DATE '2020-07-07', 'mandala',
     $rsv$Anillos concéntricos que se tejen hacia adentro, un mandala trazado en una sola pulsación. Es un recordatorio de que el orden puede aparecer sin manos que lo tracen. El campo de Stanton St. Bernard, Wiltshire lo recibió el 7 de julio de 2020.$rsv$,
     $rsv$Concentric rings weaving inward, a mandala traced in a single pulse. It is a reminder that order can appear with no hands to trace it. The field at Stanton St. Bernard, Wiltshire received it on 7 July 2020.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2020/07/1.-Stanton-St-Bernard-Wilts-07-07-20-OHS.jpg$rsv$, true, now()),
    ('038246c4-e755-5231-8cc9-248d629c9fff',
     $rsv$Berwick Bassett$rsv$, $rsv$Berwick Bassett, Wiltshire$rsv$, $rsv$Reino Unido$rsv$,
     51.46, -1.86, DATE '2020-06-21', 'grid',
     $rsv$Una retícula de nodos y celdas, un campo de señal ordenado como un idioma. El patrón se siente antiguo y recién nacido al mismo tiempo. Registrado en Berwick Bassett, Wiltshire, 21 de junio de 2020.$rsv$,
     $rsv$A lattice of nodes and cells, a signal field ordered like a language. The pattern feels ancient and newborn at once. Recorded at Berwick Bassett, Wiltshire, 21 June 2020.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2020/06/1-Berwick-Bassett-Clump-Wilts-21-06-20-OH-.jpg$rsv$, true, now()),
    ('cc83c526-baab-5256-91da-ce6d6b1df1b5',
     $rsv$Wilton$rsv$, $rsv$Wilton, Wiltshire$rsv$, $rsv$Reino Unido$rsv$,
     51.355, -1.63, DATE '2020-06-17', 'orbits',
     $rsv$Órbitas anidadas alrededor de un centro encendido, un mapa de cuerpos en movimiento. Su silencio dice más que cualquier explicación. Se abrió sobre Wilton, Wiltshire el 17 de junio de 2020.$rsv$,
     $rsv$Nested orbits around a lit center, a map of bodies in motion. Its silence says more than any explanation. It opened over Wilton, Wiltshire on 17 June 2020.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2020/06/Hunts-Down-nr-Wilton-Wilts-17-06-20-OHTIM.jpg$rsv$, true, now()),
    ('0d4ab3d2-b101-59ad-b1af-37df7982af36',
     $rsv$Burderop Down$rsv$, $rsv$Burderop Down, Wiltshire$rsv$, $rsv$Reino Unido$rsv$,
     51.485, -1.78, DATE '2020-06-14', 'mandala',
     $rsv$Anillos concéntricos que se tejen hacia adentro, un mandala trazado en una sola pulsación. La forma sostiene una tensión perfecta entre lo vacío y lo lleno. Coordenada sellada: Burderop Down, Wiltshire, 14 de junio de 2020.$rsv$,
     $rsv$Concentric rings weaving inward, a mandala traced in a single pulse. The form holds a perfect tension between the empty and the full. Sealed coordinate: Burderop Down, Wiltshire, 14 June 2020.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2020/06/2.-Burderop-Down-Barbury-Castle-Wilts-14-06-20-OH2.jpg$rsv$, true, now()),
    ('fa4457a7-eb18-5257-a5e3-1f9aedd15771',
     $rsv$Dilton Marsh$rsv$, $rsv$Dilton Marsh, Wiltshire$rsv$, $rsv$Reino Unido$rsv$,
     51.26, -2.23, DATE '2020-06-11', 'spiral',
     $rsv$Un brazo en espiral que gira desde un núcleo brillante, la geometría del crecimiento hecha visible. Late como una señal que espera ser reconocida, no descifrada. Dilton Marsh, Wiltshire guarda su huella desde el 11 de junio de 2020.$rsv$,
     $rsv$A spiral arm turning out from a bright core, the geometry of growth made visible. It pulses like a signal waiting to be recognized, not decoded. Dilton Marsh, Wiltshire has held its mark since 11 June 2020.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2020/06/2.-Hoopers-Wood-Dilton-Marsh-Wilts-11-06-20-OH2.jpg$rsv$, true, now()),
    ('41155ec8-813f-5401-b853-1c9652e466c2',
     $rsv$Sixpenny Handley$rsv$, $rsv$Sixpenny Handley, Dorset$rsv$, $rsv$Reino Unido$rsv$,
     50.958, -2.01, DATE '2020-05-31', 'grid',
     $rsv$Una retícula de nodos y celdas, un campo de señal ordenado como un idioma. Es geometría que respira, no un dibujo que se queda quieto. Detectado en Sixpenny Handley, Dorset, 31 de mayo de 2020, y aún resuena.$rsv$,
     $rsv$A lattice of nodes and cells, a signal field ordered like a language. It is geometry that breathes, not a drawing that stays still. Detected at Sixpenny Handley, Dorset, 31 May 2020, and it still resonates.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2020/06/1.-Sixpenny-Handley-Dorset-31-05-20-OH.jpg$rsv$, true, now()),
    ('80f41906-0efd-5cb2-9ea1-51b78032d2c7',
     $rsv$Cley Hill$rsv$, $rsv$Cley Hill, Wiltshire$rsv$, $rsv$Reino Unido$rsv$,
     51.2, -2.25, DATE '2020-05-30', 'web',
     $rsv$Una malla hexagonal de varias capas, la estructura misma del espacio dibujada sobre el campo. Marca un punto del campo donde la belleza se volvió tecnología de apertura. El campo de Cley Hill, Wiltshire lo recibió el 30 de mayo de 2020.$rsv$,
     $rsv$A many-layered hexagonal mesh, the structure of space itself drawn onto the field. It marks a point in the field where beauty became a technology of opening. The field at Cley Hill, Wiltshire received it on 30 May 2020.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2020/06/2.Cley-Hill-Wilts-30-05-20-OH2.jpg$rsv$, true, now()),
    ('c392e137-244d-5f8a-9653-7f1c7f5faf56',
     $rsv$Potterne$rsv$, $rsv$Potterne, Wiltshire$rsv$, $rsv$Reino Unido$rsv$,
     51.335, -2.007, DATE '2020-05-28', 'mandala',
     $rsv$Anillos concéntricos que se tejen hacia adentro, un mandala trazado en una sola pulsación. No entrega un mensaje para leer: entrega un estado para sentir. Registrado en Potterne, Wiltshire, 28 de mayo de 2020.$rsv$,
     $rsv$Concentric rings weaving inward, a mandala traced in a single pulse. It delivers no message to read: it delivers a state to feel. Recorded at Potterne, Wiltshire, 28 May 2020.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2020/06/1.-Potterne-Field-Wilts-28-05-20-OH.jpg$rsv$, true, now()),
    ('f360ebee-6336-5a80-8131-d4418d068899',
     $rsv$Roundway Hill$rsv$, $rsv$Roundway Hill, Wiltshire$rsv$, $rsv$Reino Unido$rsv$,
     51.378, -1.975, DATE '2021-08-15', 'orbits',
     $rsv$Órbitas anidadas alrededor de un centro encendido, un mapa de cuerpos en movimiento. Apareció sin proceso visible, sobre un campo que horas antes estaba intacto. Se abrió sobre Roundway Hill, Wiltshire el 15 de agosto de 2021.$rsv$,
     $rsv$Nested orbits around a lit center, a map of bodies in motion. It appeared with no visible process, over a field that hours earlier was untouched. It opened over Roundway Hill, Wiltshire on 15 August 2021.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2021/08/1b.-Roundway-Hill-Wilts-15-08-21-OH.jpg$rsv$, true, now()),
    ('e03f3ee5-faf1-50ff-bf51-b29b0b6e63d8',
     $rsv$Watership Down$rsv$, $rsv$Watership Down, Hampshire$rsv$, $rsv$Reino Unido$rsv$,
     51.29, -1.29, DATE '2021-08-11', 'mandala',
     $rsv$Anillos concéntricos que se tejen hacia adentro, un mandala trazado en una sola pulsación. La proporción entre sus radios cae en números limpios, la matemática que no depende de ningún idioma. Coordenada sellada: Watership Down, Hampshire, 11 de agosto de 2021.$rsv$,
     $rsv$Concentric rings weaving inward, a mandala traced in a single pulse. The ratio between its radii falls on clean numbers, the mathematics that depends on no language. Sealed coordinate: Watership Down, Hampshire, 11 August 2021.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2021/08/2.-Watership-Down-Sydmonton-Hants-11-08-21-OH.jpg$rsv$, true, now()),
    ('4aca484b-c649-505d-93d2-4846647d303a',
     $rsv$Marten$rsv$, $rsv$Marten, Wiltshire$rsv$, $rsv$Reino Unido$rsv$,
     51.33, -1.605, DATE '2021-08-08', 'grid',
     $rsv$Una retícula de nodos y celdas, un campo de señal ordenado como un idioma. Quien camina su centro reporta un cambio de frecuencia difícil de poner en palabras. Marten, Wiltshire guarda su huella desde el 8 de agosto de 2021.$rsv$,
     $rsv$A lattice of nodes and cells, a signal field ordered like a language. Those who walk its center report a shift in frequency hard to put into words. Marten, Wiltshire has held its mark since 8 August 2021.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2021/08/2.-Roman-Rd-Marten-Wilts-08-08-21-Low.jpg$rsv$, true, now()),
    ('60b9bbf0-79a2-5af2-a8ad-f011f9ce83e5',
     $rsv$West Meon$rsv$, $rsv$West Meon, Hampshire$rsv$, $rsv$Reino Unido$rsv$,
     51.01, -1.085, DATE '2021-08-08', 'tri',
     $rsv$Tres brazos en simetría perfecta alrededor de un centro, la firma de lo ternario. Su simetría es demasiado exacta para el azar y demasiado serena para el ruido. Detectado en West Meon, Hampshire, 8 de agosto de 2021, y aún resuena.$rsv$,
     $rsv$Three arms in perfect symmetry around a center, the signature of the threefold. Its symmetry is too exact for chance and too calm for noise. Detected at West Meon, Hampshire, 8 August 2021, and it still resonates.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2021/08/1.-Kitts-Ln-West-Meon-Hants-08-08-21-OH.jpg$rsv$, true, now()),
    ('fa13e011-8bae-5d0c-bb8f-c099aad6cf83',
     $rsv$Swarraton$rsv$, $rsv$Swarraton, Hampshire$rsv$, $rsv$Reino Unido$rsv$,
     51.15, -1.23, DATE '2021-08-01', 'spiral',
     $rsv$Un brazo en espiral que gira desde un núcleo brillante, la geometría del crecimiento hecha visible. Es un recordatorio de que el orden puede aparecer sin manos que lo tracen. El campo de Swarraton, Hampshire lo recibió el 1 de agosto de 2021.$rsv$,
     $rsv$A spiral arm turning out from a bright core, the geometry of growth made visible. It is a reminder that order can appear with no hands to trace it. The field at Swarraton, Hampshire received it on 1 August 2021.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2021/08/2.-Spiers-Lane-Swarraton-Hants-01-08-21-OH2.jpg$rsv$, true, now()),
    ('df6e62f0-d99b-5cbf-a6bb-a7ed54772b7c',
     $rsv$Tufton$rsv$, $rsv$Tufton, Hampshire$rsv$, $rsv$Reino Unido$rsv$,
     51.24, -1.36, DATE '2021-07-20', 'mandala',
     $rsv$Anillos concéntricos que se tejen hacia adentro, un mandala trazado en una sola pulsación. El patrón se siente antiguo y recién nacido al mismo tiempo. Registrado en Tufton, Hampshire, 20 de julio de 2021.$rsv$,
     $rsv$Concentric rings weaving inward, a mandala traced in a single pulse. The pattern feels ancient and newborn at once. Recorded at Tufton, Hampshire, 20 July 2021.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2021/07/1.-Tufton-Hants-20-07-21-OH.jpg$rsv$, true, now()),
    ('fba20192-bf1d-5d2e-b19c-798dd644e1fd',
     $rsv$Upham$rsv$, $rsv$Upham, Hampshire$rsv$, $rsv$Reino Unido$rsv$,
     50.985, -1.23, DATE '2021-07-18', 'mandala',
     $rsv$Anillos concéntricos que se tejen hacia adentro, un mandala trazado en una sola pulsación. Su silencio dice más que cualquier explicación. Se abrió sobre Upham, Hampshire el 18 de julio de 2021.$rsv$,
     $rsv$Concentric rings weaving inward, a mandala traced in a single pulse. Its silence says more than any explanation. It opened over Upham, Hampshire on 18 July 2021.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2021/07/1.-Uphan-Hants-18-07-21-OH.jpg$rsv$, true, now()),
    ('4f7f5df3-6a38-58cd-b2c6-436149038cdb',
     $rsv$Longwood Warren$rsv$, $rsv$Longwood Warren, Hampshire$rsv$, $rsv$Reino Unido$rsv$,
     51.04, -1.257, DATE '2021-07-04', 'mandala',
     $rsv$Anillos concéntricos que se tejen hacia adentro, un mandala trazado en una sola pulsación. La forma sostiene una tensión perfecta entre lo vacío y lo lleno. Coordenada sellada: Longwood Warren, Hampshire, 4 de julio de 2021.$rsv$,
     $rsv$Concentric rings weaving inward, a mandala traced in a single pulse. The form holds a perfect tension between the empty and the full. Sealed coordinate: Longwood Warren, Hampshire, 4 July 2021.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2021/07/1.-Longwood-Warren-Hants-04-07-21-OHSA--400x284.jpg$rsv$, true, now()),
    ('dc0913c9-f50a-5557-aca4-35bbabdd3424',
     $rsv$Avebury$rsv$, $rsv$Avebury, Wiltshire$rsv$, $rsv$Reino Unido$rsv$,
     51.428, -1.854, DATE '2021-07-02', 'web',
     $rsv$Una malla hexagonal de varias capas, la estructura misma del espacio dibujada sobre el campo. Late como una señal que espera ser reconocida, no descifrada. Avebury, Wiltshire guarda su huella desde el 2 de julio de 2021.$rsv$,
     $rsv$A many-layered hexagonal mesh, the structure of space itself drawn onto the field. It pulses like a signal waiting to be recognized, not decoded. Avebury, Wiltshire has held its mark since 2 July 2021.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2021/07/2.-Avebury-Stone-Circle-Wilts-02-07-21-OHSA.jpg$rsv$, true, now()),
    ('d8759f5b-e480-5a81-a9bf-c753fce142c9',
     $rsv$Tidcombe Down$rsv$, $rsv$Tidcombe Down, Wiltshire$rsv$, $rsv$Reino Unido$rsv$,
     51.32, -1.56, DATE '2021-06-28', 'grid',
     $rsv$Una retícula de nodos y celdas, un campo de señal ordenado como un idioma. Es geometría que respira, no un dibujo que se queda quieto. Detectado en Tidcombe Down, Wiltshire, 28 de junio de 2021, y aún resuena.$rsv$,
     $rsv$A lattice of nodes and cells, a signal field ordered like a language. It is geometry that breathes, not a drawing that stays still. Detected at Tidcombe Down, Wiltshire, 28 June 2021, and it still resonates.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2021/07/1.Tidcombe-Down-Wilts-28-06-21-OH-400x284.jpg$rsv$, true, now()),
    ('8d1c7f48-0ce7-5460-871a-ebd1b70b7d54',
     $rsv$Fulley Wood$rsv$, $rsv$Fulley Wood, Hampshire$rsv$, $rsv$Reino Unido$rsv$,
     51.1, -1.15, DATE '2021-06-21', 'web',
     $rsv$Una malla hexagonal de varias capas, la estructura misma del espacio dibujada sobre el campo. Marca un punto del campo donde la belleza se volvió tecnología de apertura. El campo de Fulley Wood, Hampshire lo recibió el 21 de junio de 2021.$rsv$,
     $rsv$A many-layered hexagonal mesh, the structure of space itself drawn onto the field. It marks a point in the field where beauty became a technology of opening. The field at Fulley Wood, Hampshire received it on 21 June 2021.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2021/06/2.-Fulley-Wood-Hants-21-06-21-OH2.jpg$rsv$, true, now()),
    ('d262d85c-ae5f-5b1a-93d5-50d2bb5af7d3',
     $rsv$Ludgershall$rsv$, $rsv$Ludgershall, Wiltshire$rsv$, $rsv$Reino Unido$rsv$,
     51.26, -1.62, DATE '2021-06-14', 'spiral',
     $rsv$Un brazo en espiral que gira desde un núcleo brillante, la geometría del crecimiento hecha visible. No entrega un mensaje para leer: entrega un estado para sentir. Registrado en Ludgershall, Wiltshire, 14 de junio de 2021.$rsv$,
     $rsv$A spiral arm turning out from a bright core, the geometry of growth made visible. It delivers no message to read: it delivers a state to feel. Recorded at Ludgershall, Wiltshire, 14 June 2021.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2021/06/Ludgershall-Wilts-14th-June-2021-Barley-OHH.jpg$rsv$, true, now()),
    ('f9fe0720-e541-5e81-bba1-afeb3c37dce9',
     $rsv$Wootton Rivers$rsv$, $rsv$Wootton Rivers, Wiltshire$rsv$, $rsv$Reino Unido$rsv$,
     51.36, -1.72, DATE '2021-06-09', 'orbits',
     $rsv$Órbitas anidadas alrededor de un centro encendido, un mapa de cuerpos en movimiento. Apareció sin proceso visible, sobre un campo que horas antes estaba intacto. Se abrió sobre Wootton Rivers, Wiltshire el 9 de junio de 2021.$rsv$,
     $rsv$Nested orbits around a lit center, a map of bodies in motion. It appeared with no visible process, over a field that hours earlier was untouched. It opened over Wootton Rivers, Wiltshire on 9 June 2021.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2021/06/2.-Wooton-Rivers-Wilts-09-06-21-OH2.jpg$rsv$, true, now()),
    ('31cd24bb-9da1-58c2-899b-c0f3d61ebcc4',
     $rsv$South Wonston$rsv$, $rsv$South Wonston, Hampshire$rsv$, $rsv$Reino Unido$rsv$,
     51.13, -1.32, DATE '2021-06-08', 'web',
     $rsv$Una malla hexagonal de varias capas, la estructura misma del espacio dibujada sobre el campo. La proporción entre sus radios cae en números limpios, la matemática que no depende de ningún idioma. Coordenada sellada: South Wonston, Hampshire, 8 de junio de 2021.$rsv$,
     $rsv$A many-layered hexagonal mesh, the structure of space itself drawn onto the field. The ratio between its radii falls on clean numbers, the mathematics that depends on no language. Sealed coordinate: South Wonston, Hampshire, 8 June 2021.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2021/06/3.-South-Wonston-Hants-08-06-21-L.jpg$rsv$, true, now()),
    ('20b36f1b-939c-5b41-ba8b-fbe628218fb8',
     $rsv$Stanton St. Bernard$rsv$, $rsv$Stanton St. Bernard, Wiltshire$rsv$, $rsv$Reino Unido$rsv$,
     51.37, -1.898, DATE '2021-05-10', 'spiral',
     $rsv$Un brazo en espiral que gira desde un núcleo brillante, la geometría del crecimiento hecha visible. Quien camina su centro reporta un cambio de frecuencia difícil de poner en palabras. Stanton St. Bernard, Wiltshire guarda su huella desde el 10 de mayo de 2021.$rsv$,
     $rsv$A spiral arm turning out from a bright core, the geometry of growth made visible. Those who walk its center report a shift in frequency hard to put into words. Stanton St. Bernard, Wiltshire has held its mark since 10 May 2021.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2021/05/1.-Stanton-St-Bernard-10-05-21-OH.jpg$rsv$, true, now()),
    ('56181dbb-cd8f-50f6-9ec2-9adb2320ba2f',
     $rsv$Etchilhampton (2)$rsv$, $rsv$Etchilhampton, Wiltshire$rsv$, $rsv$Reino Unido$rsv$,
     51.339, -1.929, DATE '2022-08-08', 'web',
     $rsv$Una malla hexagonal de varias capas, la estructura misma del espacio dibujada sobre el campo. Su simetría es demasiado exacta para el azar y demasiado serena para el ruido. Detectado en Etchilhampton, Wiltshire, 8 de agosto de 2022, y aún resuena.$rsv$,
     $rsv$A many-layered hexagonal mesh, the structure of space itself drawn onto the field. Its symmetry is too exact for chance and too calm for noise. Detected at Etchilhampton, Wiltshire, 8 August 2022, and it still resonates.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2022/08/Etchilhampton-Hill-08-08-22-website-1.jpg$rsv$, true, now()),
    ('79339796-44ac-5721-8ab0-e86c531f42f1',
     $rsv$Alton Priors$rsv$, $rsv$Alton Priors, Wiltshire$rsv$, $rsv$Reino Unido$rsv$,
     51.355, -1.843, DATE '2022-08-03', 'web',
     $rsv$Una malla hexagonal de varias capas, la estructura misma del espacio dibujada sobre el campo. Es un recordatorio de que el orden puede aparecer sin manos que lo tracen. El campo de Alton Priors, Wiltshire lo recibió el 3 de agosto de 2022.$rsv$,
     $rsv$A many-layered hexagonal mesh, the structure of space itself drawn onto the field. It is a reminder that order can appear with no hands to trace it. The field at Alton Priors, Wiltshire received it on 3 August 2022.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2022/08/80.-Alton-Priors-Wilts-03-08-22-OH4.jpg$rsv$, true, now()),
    ('24f8ed32-07a9-58ca-bfd2-00e21827b1d6',
     $rsv$Tawsmead Copse$rsv$, $rsv$Tawsmead Copse, Wiltshire$rsv$, $rsv$Reino Unido$rsv$,
     51.352, -1.815, DATE '2022-07-27', 'mandala',
     $rsv$Anillos concéntricos que se tejen hacia adentro, un mandala trazado en una sola pulsación. El patrón se siente antiguo y recién nacido al mismo tiempo. Registrado en Tawsmead Copse, Wiltshire, 27 de julio de 2022.$rsv$,
     $rsv$Concentric rings weaving inward, a mandala traced in a single pulse. The pattern feels ancient and newborn at once. Recorded at Tawsmead Copse, Wiltshire, 27 July 2022.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2022/07/62.Tawsmead-Copse-Wilts-OH3cal.jpg$rsv$, true, now()),
    ('f048971d-0f7e-5dbd-9ceb-9e18401eb697',
     $rsv$Etchilhampton$rsv$, $rsv$Etchilhampton, Wiltshire$rsv$, $rsv$Reino Unido$rsv$,
     51.339, -1.929, DATE '2022-07-24', 'orbits',
     $rsv$Órbitas anidadas alrededor de un centro encendido, un mapa de cuerpos en movimiento. Su silencio dice más que cualquier explicación. Se abrió sobre Etchilhampton, Wiltshire el 24 de julio de 2022.$rsv$,
     $rsv$Nested orbits around a lit center, a map of bodies in motion. Its silence says more than any explanation. It opened over Etchilhampton, Wiltshire on 24 July 2022.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2022/07/50.-Etchilhampton-Hill-Wilts-24-07-22-OH.jpg$rsv$, true, now()),
    ('ef34dcc1-08c6-5f95-9e50-a0ee0ffafebb',
     $rsv$Barbury Castle$rsv$, $rsv$Barbury Castle, Wiltshire$rsv$, $rsv$Reino Unido$rsv$,
     51.485, -1.78, DATE '2022-07-17', 'grid',
     $rsv$Una retícula de nodos y celdas, un campo de señal ordenado como un idioma. La forma sostiene una tensión perfecta entre lo vacío y lo lleno. Coordenada sellada: Barbury Castle, Wiltshire, 17 de julio de 2022.$rsv$,
     $rsv$A lattice of nodes and cells, a signal field ordered like a language. The form holds a perfect tension between the empty and the full. Sealed coordinate: Barbury Castle, Wiltshire, 17 July 2022.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2022/07/38.-Barbury-Castle-Wilts-17-07-22-OH-.jpg$rsv$, true, now()),
    ('4255e3db-f6b5-5b49-8261-2959f6077bf5',
     $rsv$Little Horton$rsv$, $rsv$Little Horton, Wiltshire$rsv$, $rsv$Reino Unido$rsv$,
     51.36, -1.96, DATE '2022-07-14', 'web',
     $rsv$Una malla hexagonal de varias capas, la estructura misma del espacio dibujada sobre el campo. Late como una señal que espera ser reconocida, no descifrada. Little Horton, Wiltshire guarda su huella desde el 14 de julio de 2022.$rsv$,
     $rsv$A many-layered hexagonal mesh, the structure of space itself drawn onto the field. It pulses like a signal waiting to be recognized, not decoded. Little Horton, Wiltshire has held its mark since 14 July 2022.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2022/07/31.-Lay-Wood-Devizes-14-07-22-OH.jpg$rsv$, true, now()),
    ('2c6e3152-428d-589a-a6a4-acb31a6cad30',
     $rsv$Chilcomb$rsv$, $rsv$Chilcomb, Hampshire$rsv$, $rsv$Reino Unido$rsv$,
     51.04, -1.27, DATE '2022-07-12', 'spiral',
     $rsv$Un brazo en espiral que gira desde un núcleo brillante, la geometría del crecimiento hecha visible. Es geometría que respira, no un dibujo que se queda quieto. Detectado en Chilcomb, Hampshire, 12 de julio de 2022, y aún resuena.$rsv$,
     $rsv$A spiral arm turning out from a bright core, the geometry of growth made visible. It is geometry that breathes, not a drawing that stays still. Detected at Chilcomb, Hampshire, 12 July 2022, and it still resonates.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2022/07/25.-Morestead-Hants-12-07-22-OH.jpg$rsv$, true, now()),
    ('22d139d9-21f7-57a5-877b-1543c93ca9cd',
     $rsv$Froxfield$rsv$, $rsv$Froxfield, Wiltshire$rsv$, $rsv$Reino Unido$rsv$,
     51.41, -1.56, DATE '2022-07-09', 'orbits',
     $rsv$Órbitas anidadas alrededor de un centro encendido, un mapa de cuerpos en movimiento. Marca un punto del campo donde la belleza se volvió tecnología de apertura. El campo de Froxfield, Wiltshire lo recibió el 9 de julio de 2022.$rsv$,
     $rsv$Nested orbits around a lit center, a map of bodies in motion. It marks a point in the field where beauty became a technology of opening. The field at Froxfield, Wiltshire received it on 9 July 2022.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2022/07/1.-Cake-Wood-Froxfield-Wilts-09-07-22-Barley-OHHF.jpg$rsv$, true, now()),
    ('dec21b9f-67a6-5f93-bfba-c394ec2a4ac2',
     $rsv$Micheldever Station$rsv$, $rsv$Micheldever Station, Hampshire$rsv$, $rsv$Reino Unido$rsv$,
     51.15, -1.27, DATE '2022-07-03', 'mandala',
     $rsv$Anillos concéntricos que se tejen hacia adentro, un mandala trazado en una sola pulsación. No entrega un mensaje para leer: entrega un estado para sentir. Registrado en Micheldever Station, Hampshire, 3 de julio de 2022.$rsv$,
     $rsv$Concentric rings weaving inward, a mandala traced in a single pulse. It delivers no message to read: it delivers a state to feel. Recorded at Micheldever Station, Hampshire, 3 July 2022.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2022/07/15.-Micheldever-Station-Hants-03-07-22-Wheat-OH.jpg$rsv$, true, now()),
    ('7f9265ca-7961-58fe-b23f-098649f3d67c',
     $rsv$Hackpen Hill (2)$rsv$, $rsv$Hackpen Hill, Wiltshire$rsv$, $rsv$Reino Unido$rsv$,
     51.47, -1.83, DATE '2022-06-19', 'tri',
     $rsv$Tres brazos en simetría perfecta alrededor de un centro, la firma de lo ternario. Apareció sin proceso visible, sobre un campo que horas antes estaba intacto. Se abrió sobre Hackpen Hill, Wiltshire el 19 de junio de 2022.$rsv$,
     $rsv$Three arms in perfect symmetry around a center, the signature of the threefold. It appeared with no visible process, over a field that hours earlier was untouched. It opened over Hackpen Hill, Wiltshire on 19 June 2022.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2022/06/5.-Hackpen-Hill-Wilts-19-06-22-OH.jpg$rsv$, true, now()),
    ('aa9d852a-64f1-5892-b372-ea2845d1d08a',
     $rsv$Hackpen Hill (1)$rsv$, $rsv$Hackpen Hill, Wiltshire$rsv$, $rsv$Reino Unido$rsv$,
     51.47, -1.83, DATE '2022-06-04', 'orbits',
     $rsv$Órbitas anidadas alrededor de un centro encendido, un mapa de cuerpos en movimiento. La proporción entre sus radios cae en números limpios, la matemática que no depende de ningún idioma. Coordenada sellada: Hackpen Hill, Wiltshire, 4 de junio de 2022.$rsv$,
     $rsv$Nested orbits around a lit center, a map of bodies in motion. The ratio between its radii falls on clean numbers, the mathematics that depends on no language. Sealed coordinate: Hackpen Hill, Wiltshire, 4 June 2022.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2022/06/1.Owl-House-Hackpen-Hill-Wilts-04-06-22-OH.jpg$rsv$, true, now()),
    ('12303867-e7b1-5d72-9ae8-7718fb2166f0',
     $rsv$Hippenscombe$rsv$, $rsv$Hippenscombe, Wiltshire$rsv$, $rsv$Reino Unido$rsv$,
     51.32, -1.52, DATE '2022-05-22', 'grid',
     $rsv$Una retícula de nodos y celdas, un campo de señal ordenado como un idioma. Quien camina su centro reporta un cambio de frecuencia difícil de poner en palabras. Hippenscombe, Wiltshire guarda su huella desde el 22 de mayo de 2022.$rsv$,
     $rsv$A lattice of nodes and cells, a signal field ordered like a language. Those who walk its center report a shift in frequency hard to put into words. Hippenscombe, Wiltshire has held its mark since 22 May 2022.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2022/05/1.-Little-Down-nr-Hippenscombe-Wilts-22-05-22-Barley-HFOH-.jpg$rsv$, true, now()),
    ('d7d34340-9c2b-5d26-bfb2-128d5962b6e5',
     $rsv$Crab Wood$rsv$, $rsv$Crab Wood, Hampshire$rsv$, $rsv$Reino Unido$rsv$,
     51.065, -1.36, DATE '2022-04-24', 'orbits',
     $rsv$Órbitas anidadas alrededor de un centro encendido, un mapa de cuerpos en movimiento. Su simetría es demasiado exacta para el azar y demasiado serena para el ruido. Detectado en Crab Wood, Hampshire, 24 de abril de 2022, y aún resuena.$rsv$,
     $rsv$Nested orbits around a lit center, a map of bodies in motion. Its symmetry is too exact for chance and too calm for noise. Detected at Crab Wood, Hampshire, 24 April 2022, and it still resonates.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2022/04/1.-Crab-Wood-Winchester-Hants-24-04-22-OSR-OH-1.jpg$rsv$, true, now()),
    ('edc40b97-3083-5b96-b937-d515932a6a33',
     $rsv$Roundway Hill$rsv$, $rsv$Roundway Hill, Wiltshire$rsv$, $rsv$Reino Unido$rsv$,
     51.378, -1.975, DATE '2023-08-13', 'orbits',
     $rsv$Órbitas anidadas alrededor de un centro encendido, un mapa de cuerpos en movimiento. Es un recordatorio de que el orden puede aparecer sin manos que lo tracen. El campo de Roundway Hill, Wiltshire lo recibió el 13 de agosto de 2023.$rsv$,
     $rsv$Nested orbits around a lit center, a map of bodies in motion. It is a reminder that order can appear with no hands to trace it. The field at Roundway Hill, Wiltshire received it on 13 August 2023.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2023/08/DSC5641-Roundway-Wilts-13-08-23-OH.jpg$rsv$, true, now()),
    ('474f553a-5b8c-523c-a255-b8357e3b49d5',
     $rsv$Cley Hill$rsv$, $rsv$Cley Hill, Wiltshire$rsv$, $rsv$Reino Unido$rsv$,
     51.2, -2.25, DATE '2023-08-10', 'mandala',
     $rsv$Anillos concéntricos que se tejen hacia adentro, un mandala trazado en una sola pulsación. El patrón se siente antiguo y recién nacido al mismo tiempo. Registrado en Cley Hill, Wiltshire, 10 de agosto de 2023.$rsv$,
     $rsv$Concentric rings weaving inward, a mandala traced in a single pulse. The pattern feels ancient and newborn at once. Recorded at Cley Hill, Wiltshire, 10 August 2023.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2023/08/DSC5629-Cley-Hill-Wilts-10-08-23-OH-1.jpg$rsv$, true, now()),
    ('e41757d9-6ca7-5966-9709-e34f1ba24554',
     $rsv$Wayland's Smithy$rsv$, $rsv$Wayland's Smithy, Oxfordshire$rsv$, $rsv$Reino Unido$rsv$,
     51.567, -1.596, DATE '2023-08-04', 'orbits',
     $rsv$Órbitas anidadas alrededor de un centro encendido, un mapa de cuerpos en movimiento. Su silencio dice más que cualquier explicación. Se abrió sobre Wayland's Smithy, Oxfordshire el 4 de agosto de 2023.$rsv$,
     $rsv$Nested orbits around a lit center, a map of bodies in motion. Its silence says more than any explanation. It opened over Wayland's Smithy, Oxfordshire on 4 August 2023.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2023/08/DSC5626-Waylands-Smithy-04-08-2023-OH.jpg$rsv$, true, now()),
    ('3451e902-fe34-5ecc-a2f0-1255578e6dc6',
     $rsv$Preston Candover$rsv$, $rsv$Preston Candover, Hampshire$rsv$, $rsv$Reino Unido$rsv$,
     51.17, -1.1, DATE '2023-08-02', 'web',
     $rsv$Una malla hexagonal de varias capas, la estructura misma del espacio dibujada sobre el campo. La forma sostiene una tensión perfecta entre lo vacío y lo lleno. Coordenada sellada: Preston Candover, Hampshire, 2 de agosto de 2023.$rsv$,
     $rsv$A many-layered hexagonal mesh, the structure of space itself drawn onto the field. The form holds a perfect tension between the empty and the full. Sealed coordinate: Preston Candover, Hampshire, 2 August 2023.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2023/08/DSC5603-Preston-Candover-Hants-02-08-23-OH3.jpg$rsv$, true, now()),
    ('f40cb762-bc87-52df-a60c-3b7967771c8a',
     $rsv$Westbury$rsv$, $rsv$Westbury, Wiltshire$rsv$, $rsv$Reino Unido$rsv$,
     51.26, -2.19, DATE '2023-07-30', 'mandala',
     $rsv$Anillos concéntricos que se tejen hacia adentro, un mandala trazado en una sola pulsación. Late como una señal que espera ser reconocida, no descifrada. Westbury, Wiltshire guarda su huella desde el 30 de julio de 2023.$rsv$,
     $rsv$Concentric rings weaving inward, a mandala traced in a single pulse. It pulses like a signal waiting to be recognized, not decoded. Westbury, Wiltshire has held its mark since 30 July 2023.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2023/08/Westbury-30-07-23-HN2-144-1.jpg$rsv$, true, now()),
    ('555fc521-a1c1-583d-a377-ccd012d7007d',
     $rsv$West Meon$rsv$, $rsv$West Meon, Hampshire$rsv$, $rsv$Reino Unido$rsv$,
     51.01, -1.085, DATE '2023-07-30', 'tri',
     $rsv$Tres brazos en simetría perfecta alrededor de un centro, la firma de lo ternario. Es geometría que respira, no un dibujo que se queda quieto. Detectado en West Meon, Hampshire, 30 de julio de 2023, y aún resuena.$rsv$,
     $rsv$Three arms in perfect symmetry around a center, the signature of the threefold. It is geometry that breathes, not a drawing that stays still. Detected at West Meon, Hampshire, 30 July 2023, and it still resonates.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2023/08/DSC5553-West-Meon-Hants-30-07-23-OH.jpg$rsv$, true, now()),
    ('82bd0d2b-932e-5680-bf69-5016e0df29d3',
     $rsv$Charlton$rsv$, $rsv$Charlton, Hampshire$rsv$, $rsv$Reino Unido$rsv$,
     51.225, -1.49, DATE '2023-07-25', 'grid',
     $rsv$Una retícula de nodos y celdas, un campo de señal ordenado como un idioma. Marca un punto del campo donde la belleza se volvió tecnología de apertura. El campo de Charlton, Hampshire lo recibió el 25 de julio de 2023.$rsv$,
     $rsv$A lattice of nodes and cells, a signal field ordered like a language. It marks a point in the field where beauty became a technology of opening. The field at Charlton, Hampshire received it on 25 July 2023.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2023/08/DSC5539-Charlton-Hants-25-07-23-OH-1.jpg$rsv$, true, now()),
    ('8620c331-ad57-5fde-aac6-6293cce63d33',
     $rsv$Barton Stacey Belt$rsv$, $rsv$Barton Stacey Belt, Hampshire$rsv$, $rsv$Reino Unido$rsv$,
     51.15, -1.4, DATE '2023-07-09', 'spiral',
     $rsv$Un brazo en espiral que gira desde un núcleo brillante, la geometría del crecimiento hecha visible. No entrega un mensaje para leer: entrega un estado para sentir. Registrado en Barton Stacey Belt, Hampshire, 9 de julio de 2023.$rsv$,
     $rsv$A spiral arm turning out from a bright core, the geometry of growth made visible. It delivers no message to read: it delivers a state to feel. Recorded at Barton Stacey Belt, Hampshire, 9 July 2023.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2023/07/DSC5509-South-Wonston-Hants-09-07-23-OH2.jpg$rsv$, true, now()),
    ('2f9b43e4-1ab8-5bc3-867d-428c38e8e4a2',
     $rsv$Lane End$rsv$, $rsv$Lane End, Hampshire$rsv$, $rsv$Reino Unido$rsv$,
     51.05, -1.23, DATE '2023-07-09', 'grid',
     $rsv$Una retícula de nodos y celdas, un campo de señal ordenado como un idioma. Apareció sin proceso visible, sobre un campo que horas antes estaba intacto. Se abrió sobre Lane End, Hampshire el 9 de julio de 2023.$rsv$,
     $rsv$A lattice of nodes and cells, a signal field ordered like a language. It appeared with no visible process, over a field that hours earlier was untouched. It opened over Lane End, Hampshire on 9 July 2023.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2023/08/DSC5575-Lane-End-Down-Hants-09-07-23-OHsun.jpg$rsv$, true, now()),
    ('e6cdf46d-fccc-569b-9879-bc579a5710d9',
     $rsv$Norton Bavant$rsv$, $rsv$Norton Bavant, Wiltshire$rsv$, $rsv$Reino Unido$rsv$,
     51.185, -2.12, DATE '2023-07-07', 'orbits',
     $rsv$Órbitas anidadas alrededor de un centro encendido, un mapa de cuerpos en movimiento. La proporción entre sus radios cae en números limpios, la matemática que no depende de ningún idioma. Coordenada sellada: Norton Bavant, Wiltshire, 7 de julio de 2023.$rsv$,
     $rsv$Nested orbits around a lit center, a map of bodies in motion. The ratio between its radii falls on clean numbers, the mathematics that depends on no language. Sealed coordinate: Norton Bavant, Wiltshire, 7 July 2023.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2023/07/1.Norton-Plantation-Nr-Norton-Bavant-Wilts-07-07-23-OH.jpg$rsv$, true, now()),
    ('07abb74d-0195-534d-8f19-11c547533188',
     $rsv$Micheldever (2)$rsv$, $rsv$Micheldever, Hampshire$rsv$, $rsv$Reino Unido$rsv$,
     51.15, -1.27, DATE '2023-07-04', 'grid',
     $rsv$Una retícula de nodos y celdas, un campo de señal ordenado como un idioma. Quien camina su centro reporta un cambio de frecuencia difícil de poner en palabras. Micheldever, Hampshire guarda su huella desde el 4 de julio de 2023.$rsv$,
     $rsv$A lattice of nodes and cells, a signal field ordered like a language. Those who walk its center report a shift in frequency hard to put into words. Micheldever, Hampshire has held its mark since 4 July 2023.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2023/07/DSC5478-Micheldever-1-Hants-04-07-23-OH.jpg$rsv$, true, now()),
    ('51bbc644-54cb-575b-acd2-c8f99039cb62',
     $rsv$Micheldever (1)$rsv$, $rsv$Micheldever, Hampshire$rsv$, $rsv$Reino Unido$rsv$,
     51.15, -1.27, DATE '2023-07-04', 'grid',
     $rsv$Una retícula de nodos y celdas, un campo de señal ordenado como un idioma. Su simetría es demasiado exacta para el azar y demasiado serena para el ruido. Detectado en Micheldever, Hampshire, 4 de julio de 2023, y aún resuena.$rsv$,
     $rsv$A lattice of nodes and cells, a signal field ordered like a language. Its symmetry is too exact for chance and too calm for noise. Detected at Micheldever, Hampshire, 4 July 2023, and it still resonates.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2023/07/DSC5480-Micheldever-2-Hants-04-07-23-OH.jpg$rsv$, true, now()),
    ('bdb45654-6047-571d-996e-f186f6827d1a',
     $rsv$Owslebury$rsv$, $rsv$Owslebury, Hampshire$rsv$, $rsv$Reino Unido$rsv$,
     51.02, -1.27, DATE '2023-06-26', 'spiral',
     $rsv$Un brazo en espiral que gira desde un núcleo brillante, la geometría del crecimiento hecha visible. Es un recordatorio de que el orden puede aparecer sin manos que lo tracen. El campo de Owslebury, Hampshire lo recibió el 26 de junio de 2023.$rsv$,
     $rsv$A spiral arm turning out from a bright core, the geometry of growth made visible. It is a reminder that order can appear with no hands to trace it. The field at Owslebury, Hampshire received it on 26 June 2023.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2023/07/1.-_DSC5424-Owslebury-Hants-26-06-23-OH-Geo.jpg$rsv$, true, now()),
    ('bb20f3db-3685-51bc-ace7-1f87c481be75',
     $rsv$Bishopstrow$rsv$, $rsv$Bishopstrow, Wiltshire$rsv$, $rsv$Reino Unido$rsv$,
     51.19, -2.15, DATE '2023-06-18', 'mandala',
     $rsv$Anillos concéntricos que se tejen hacia adentro, un mandala trazado en una sola pulsación. El patrón se siente antiguo y recién nacido al mismo tiempo. Registrado en Bishopstrow, Wiltshire, 18 de junio de 2023.$rsv$,
     $rsv$Concentric rings weaving inward, a mandala traced in a single pulse. The pattern feels ancient and newborn at once. Recorded at Bishopstrow, Wiltshire, 18 June 2023.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2023/06/1.-Eastleigh-Court-Wilts-18-06-23-OH.jpg$rsv$, true, now()),
    ('4fd56979-f7d2-5fbe-ae7c-201c2b5b9f45',
     $rsv$Roundway Down$rsv$, $rsv$Roundway Down, Wiltshire$rsv$, $rsv$Reino Unido$rsv$,
     51.378, -1.975, DATE '2023-06-11', 'mandala',
     $rsv$Anillos concéntricos que se tejen hacia adentro, un mandala trazado en una sola pulsación. Su silencio dice más que cualquier explicación. Se abrió sobre Roundway Down, Wiltshire el 11 de junio de 2023.$rsv$,
     $rsv$Concentric rings weaving inward, a mandala traced in a single pulse. Its silence says more than any explanation. It opened over Roundway Down, Wiltshire on 11 June 2023.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2023/06/11-June-Roundawy.jpg$rsv$, true, now()),
    ('1e4c445c-b536-5276-95ff-03ba074b3d5b',
     $rsv$Potterne Hill$rsv$, $rsv$Potterne Hill, Wiltshire$rsv$, $rsv$Reino Unido$rsv$,
     51.335, -2.01, DATE '2023-06-07', 'mandala',
     $rsv$Anillos concéntricos que se tejen hacia adentro, un mandala trazado en una sola pulsación. La forma sostiene una tensión perfecta entre lo vacío y lo lleno. Coordenada sellada: Potterne Hill, Wiltshire, 7 de junio de 2023.$rsv$,
     $rsv$Concentric rings weaving inward, a mandala traced in a single pulse. The form holds a perfect tension between the empty and the full. Sealed coordinate: Potterne Hill, Wiltshire, 7 June 2023.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2023/06/2.-Potterne-Wilts-07-06-23-OH2.jpg$rsv$, true, now()),
    ('7197f1e0-3e96-588a-b62f-707ffd3a8ab8',
     $rsv$Winterbourne Bassett$rsv$, $rsv$Winterbourne Bassett, Wiltshire$rsv$, $rsv$Reino Unido$rsv$,
     51.45, -1.87, DATE '2023-06-04', 'orbits',
     $rsv$Órbitas anidadas alrededor de un centro encendido, un mapa de cuerpos en movimiento. Late como una señal que espera ser reconocida, no descifrada. Winterbourne Bassett, Wiltshire guarda su huella desde el 4 de junio de 2023.$rsv$,
     $rsv$Nested orbits around a lit center, a map of bodies in motion. It pulses like a signal waiting to be recognized, not decoded. Winterbourne Bassett, Wiltshire has held its mark since 4 June 2023.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2023/06/1.-Winterbourne-Bassett-04-06-23-OH.jpg$rsv$, true, now()),
    ('1f2d9dd0-37c8-545d-884b-66c4e82beaa5',
     $rsv$Broad Hinton$rsv$, $rsv$Broad Hinton, Wiltshire$rsv$, $rsv$Reino Unido$rsv$,
     51.47, -1.85, DATE '2023-05-28', 'web',
     $rsv$Una malla hexagonal de varias capas, la estructura misma del espacio dibujada sobre el campo. Es geometría que respira, no un dibujo que se queda quieto. Detectado en Broad Hinton, Wiltshire, 28 de mayo de 2023, y aún resuena.$rsv$,
     $rsv$A many-layered hexagonal mesh, the structure of space itself drawn onto the field. It is geometry that breathes, not a drawing that stays still. Detected at Broad Hinton, Wiltshire, 28 May 2023, and it still resonates.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2023/06/2.Broad-Hinton-Wilts-28-05-23-OH.jpg$rsv$, true, now()),
    ('daf2d87e-c598-5936-be72-7f2e1a84b4a7',
     $rsv$Etchilhampton Stage 2$rsv$, $rsv$Etchilhampton, Wiltshire$rsv$, $rsv$Reino Unido$rsv$,
     51.339, -1.929, DATE '2024-08-29', 'tri',
     $rsv$Tres brazos en simetría perfecta alrededor de un centro, la firma de lo ternario. Marca un punto del campo donde la belleza se volvió tecnología de apertura. El campo de Etchilhampton, Wiltshire lo recibió el 29 de agosto de 2024.$rsv$,
     $rsv$Three arms in perfect symmetry around a center, the signature of the threefold. It marks a point in the field where beauty became a technology of opening. The field at Etchilhampton, Wiltshire received it on 29 August 2024.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2024/08/1.-website-Etchilhampton-Stage-2-OH.jpg$rsv$, true, now()),
    ('cc6162cb-a146-5754-8948-0903a9c6e6e5',
     $rsv$Etchilhampton$rsv$, $rsv$Etchilhampton, Wiltshire$rsv$, $rsv$Reino Unido$rsv$,
     51.339, -1.929, DATE '2024-08-08', 'web',
     $rsv$Una malla hexagonal de varias capas, la estructura misma del espacio dibujada sobre el campo. No entrega un mensaje para leer: entrega un estado para sentir. Registrado en Etchilhampton, Wiltshire, 8 de agosto de 2024.$rsv$,
     $rsv$A many-layered hexagonal mesh, the structure of space itself drawn onto the field. It delivers no message to read: it delivers a state to feel. Recorded at Etchilhampton, Wiltshire, 8 August 2024.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2024/08/2.-Etchilhampton-Hill-Wilts-08-08-24-OH.jpg$rsv$, true, now()),
    ('d79bb36c-d192-575c-9c2d-a8480e7607ca',
     $rsv$Stoke Charity$rsv$, $rsv$Stoke Charity, Hampshire$rsv$, $rsv$Reino Unido$rsv$,
     51.15, -1.33, DATE '2024-07-28', 'orbits',
     $rsv$Órbitas anidadas alrededor de un centro encendido, un mapa de cuerpos en movimiento. Apareció sin proceso visible, sobre un campo que horas antes estaba intacto. Se abrió sobre Stoke Charity, Hampshire el 28 de julio de 2024.$rsv$,
     $rsv$Nested orbits around a lit center, a map of bodies in motion. It appeared with no visible process, over a field that hours earlier was untouched. It opened over Stoke Charity, Hampshire on 28 July 2024.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2024/07/1.-Stoke-Charity-Hants-28-07-24-OH.jpg$rsv$, true, now()),
    ('7ae5b93e-7a58-5317-8ecd-3320d41a5442',
     $rsv$Marten$rsv$, $rsv$Marten, Wiltshire$rsv$, $rsv$Reino Unido$rsv$,
     51.33, -1.605, DATE '2024-07-23', 'tri',
     $rsv$Tres brazos en simetría perfecta alrededor de un centro, la firma de lo ternario. La proporción entre sus radios cae en números limpios, la matemática que no depende de ningún idioma. Coordenada sellada: Marten, Wiltshire, 23 de julio de 2024.$rsv$,
     $rsv$Three arms in perfect symmetry around a center, the signature of the threefold. The ratio between its radii falls on clean numbers, the mathematics that depends on no language. Sealed coordinate: Marten, Wiltshire, 23 July 2024.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2024/07/1.-Marten-Wilts-23-07-24-OH.jpg$rsv$, true, now()),
    ('b3cbf8a7-090c-5a43-bad9-284c6219b664',
     $rsv$Badbury Rings$rsv$, $rsv$Badbury Rings, Dorset$rsv$, $rsv$Reino Unido$rsv$,
     50.815, -2.058, DATE '2024-07-19', 'tri',
     $rsv$Tres brazos en simetría perfecta alrededor de un centro, la firma de lo ternario. Quien camina su centro reporta un cambio de frecuencia difícil de poner en palabras. Badbury Rings, Dorset guarda su huella desde el 19 de julio de 2024.$rsv$,
     $rsv$Three arms in perfect symmetry around a center, the signature of the threefold. Those who walk its center report a shift in frequency hard to put into words. Badbury Rings, Dorset has held its mark since 19 July 2024.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2024/07/Ben-Sasson_final_20240719_202300_small.jpg$rsv$, true, now()),
    ('a7108d83-9011-59b8-8b27-fb58f5075336',
     $rsv$Normanton Down$rsv$, $rsv$Normanton Down, Wiltshire$rsv$, $rsv$Reino Unido$rsv$,
     51.17, -1.83, DATE '2024-07-14', 'web',
     $rsv$Una malla hexagonal de varias capas, la estructura misma del espacio dibujada sobre el campo. Su simetría es demasiado exacta para el azar y demasiado serena para el ruido. Detectado en Normanton Down, Wiltshire, 14 de julio de 2024, y aún resuena.$rsv$,
     $rsv$A many-layered hexagonal mesh, the structure of space itself drawn onto the field. Its symmetry is too exact for chance and too calm for noise. Detected at Normanton Down, Wiltshire, 14 July 2024, and it still resonates.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2024/07/1.-Normanton-Down-14-07-24-OH.jpg$rsv$, true, now()),
    ('d6e03918-bfa5-5285-a8bf-331d5e311836',
     $rsv$Stonehenge$rsv$, $rsv$Stonehenge, Wiltshire$rsv$, $rsv$Reino Unido$rsv$,
     51.185, -1.828, DATE '2024-06-30', 'orbits',
     $rsv$Órbitas anidadas alrededor de un centro encendido, un mapa de cuerpos en movimiento. Es un recordatorio de que el orden puede aparecer sin manos que lo tracen. El campo de Stonehenge, Wiltshire lo recibió el 30 de junio de 2024.$rsv$,
     $rsv$Nested orbits around a lit center, a map of bodies in motion. It is a reminder that order can appear with no hands to trace it. The field at Stonehenge, Wiltshire received it on 30 June 2024.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2024/07/2.Stonehenge-Visitors-Ctr-30-06-24-OH2.jpg$rsv$, true, now()),
    ('4df4ea9b-19b6-58fb-8042-e9368ef1f24c',
     $rsv$Wilton Windmill$rsv$, $rsv$Wilton Windmill, Wiltshire$rsv$, $rsv$Reino Unido$rsv$,
     51.36, -1.615, DATE '2024-06-12', 'web',
     $rsv$Una malla hexagonal de varias capas, la estructura misma del espacio dibujada sobre el campo. El patrón se siente antiguo y recién nacido al mismo tiempo. Registrado en Wilton Windmill, Wiltshire, 12 de junio de 2024.$rsv$,
     $rsv$A many-layered hexagonal mesh, the structure of space itself drawn onto the field. The pattern feels ancient and newborn at once. Recorded at Wilton Windmill, Wiltshire, 12 June 2024.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2024/06/1.-Wilton-Windmill-Wilts-12-06-24-barley-Banner-2.jpg$rsv$, true, now()),
    ('9dd73075-8cb7-52f5-8342-0a7d6c748ea1',
     $rsv$Ludwell$rsv$, $rsv$Ludwell, Wiltshire$rsv$, $rsv$Reino Unido$rsv$,
     51.01, -2.1, DATE '2025-07-12', 'grid',
     $rsv$Una retícula de nodos y celdas, un campo de señal ordenado como un idioma. Su silencio dice más que cualquier explicación. Se abrió sobre Ludwell, Wiltshire el 12 de julio de 2025.$rsv$,
     $rsv$A lattice of nodes and cells, a signal field ordered like a language. Its silence says more than any explanation. It opened over Ludwell, Wiltshire on 12 July 2025.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2025/07/Ludwell-2025-edit.jpg$rsv$, true, now()),
    ('47174a91-1b7e-506e-bd7f-7ea514e44c30',
     $rsv$Cerne Abbas$rsv$, $rsv$Cerne Abbas, Dorset$rsv$, $rsv$Reino Unido$rsv$,
     50.81, -2.475, DATE '2025-07-10', 'orbits',
     $rsv$Órbitas anidadas alrededor de un centro encendido, un mapa de cuerpos en movimiento. La forma sostiene una tensión perfecta entre lo vacío y lo lleno. Coordenada sellada: Cerne Abbas, Dorset, 10 de julio de 2025.$rsv$,
     $rsv$Nested orbits around a lit center, a map of bodies in motion. The form holds a perfect tension between the empty and the full. Sealed coordinate: Cerne Abbas, Dorset, 10 July 2025.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2025/07/1.-Cerne-Abbas-Dorset-10-07-25-OH.jpg$rsv$, true, now()),
    ('38978498-77c1-56cf-88a6-a78230047f06',
     $rsv$Castley Hill$rsv$, $rsv$Castley Hill, Somerset$rsv$, $rsv$Reino Unido$rsv$,
     51.055, -2.74, DATE '2025-07-06', 'tri',
     $rsv$Tres brazos en simetría perfecta alrededor de un centro, la firma de lo ternario. Late como una señal que espera ser reconocida, no descifrada. Castley Hill, Somerset guarda su huella desde el 6 de julio de 2025.$rsv$,
     $rsv$Three arms in perfect symmetry around a center, the signature of the threefold. It pulses like a signal waiting to be recognized, not decoded. Castley Hill, Somerset has held its mark since 6 July 2025.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2025/07/Castley-Hill-web_2025-07-09_19-56-55.jpg$rsv$, true, now()),
    ('24847d5d-b1a0-5fde-89dc-48f3bc4e38c3',
     $rsv$Ware$rsv$, $rsv$Ware, Devon$rsv$, $rsv$Reino Unido$rsv$,
     50.73, -2.96, DATE '2025-06-28', 'spiral',
     $rsv$Un brazo en espiral que gira desde un núcleo brillante, la geometría del crecimiento hecha visible. Es geometría que respira, no un dibujo que se queda quieto. Detectado en Ware, Devon, 28 de junio de 2025, y aún resuena.$rsv$,
     $rsv$A spiral arm turning out from a bright core, the geometry of growth made visible. It is geometry that breathes, not a drawing that stays still. Detected at Ware, Devon, 28 June 2025, and it still resonates.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2025/07/1.Ware-Farm-nr-Lyme-Regis-28-06-25-OH.jpg$rsv$, true, now()),
    ('c86dea23-4363-54c3-84a4-53350259f8a1',
     $rsv$Hackpen Hill$rsv$, $rsv$Hackpen Hill, Wiltshire$rsv$, $rsv$Reino Unido$rsv$,
     51.47, -1.83, DATE '2025-06-22', 'mandala',
     $rsv$Anillos concéntricos que se tejen hacia adentro, un mandala trazado en una sola pulsación. Marca un punto del campo donde la belleza se volvió tecnología de apertura. El campo de Hackpen Hill, Wiltshire lo recibió el 22 de junio de 2025.$rsv$,
     $rsv$Concentric rings weaving inward, a mandala traced in a single pulse. It marks a point in the field where beauty became a technology of opening. The field at Hackpen Hill, Wiltshire received it on 22 June 2025.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2025/07/DJI_0633-Hackpen-Hill-1.jpg$rsv$, true, now()),
    ('5b3ca10d-49ed-5863-a48c-080f9f548454',
     $rsv$Kingsdon$rsv$, $rsv$Kingsdon, Somerset$rsv$, $rsv$Reino Unido$rsv$,
     51.03, -2.7, DATE '2025-06-15', 'tri',
     $rsv$Tres brazos en simetría perfecta alrededor de un centro, la firma de lo ternario. No entrega un mensaje para leer: entrega un estado para sentir. Registrado en Kingsdon, Somerset, 15 de junio de 2025.$rsv$,
     $rsv$Three arms in perfect symmetry around a center, the signature of the threefold. It delivers no message to read: it delivers a state to feel. Recorded at Kingsdon, Somerset, 15 June 2025.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2025/06/Bondip-Hill-nr-Kingsdon-Somerset-17-06-25-OH.jpg$rsv$, true, now()),
    ('76c565bf-be66-57f0-9b8e-694c367d9114',
     $rsv$Avebury$rsv$, $rsv$Avebury, Wiltshire$rsv$, $rsv$Reino Unido$rsv$,
     51.428, -1.854, DATE '2025-06-08', 'orbits',
     $rsv$Órbitas anidadas alrededor de un centro encendido, un mapa de cuerpos en movimiento. Apareció sin proceso visible, sobre un campo que horas antes estaba intacto. Se abrió sobre Avebury, Wiltshire el 8 de junio de 2025.$rsv$,
     $rsv$Nested orbits around a lit center, a map of bodies in motion. It appeared with no visible process, over a field that hours earlier was untouched. It opened over Avebury, Wiltshire on 8 June 2025.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2025/06/Ben-Sasson_web_20250609_060840_small-2.jpg$rsv$, true, now()),
    ('9d73b6a6-e23f-54f8-8e7c-0fdda20e2c95',
     $rsv$Sutton Veny$rsv$, $rsv$Sutton Veny, Wiltshire$rsv$, $rsv$Reino Unido$rsv$,
     51.17, -2.15, DATE '2025-05-15', 'orbits',
     $rsv$Órbitas anidadas alrededor de un centro encendido, un mapa de cuerpos en movimiento. La proporción entre sus radios cae en números limpios, la matemática que no depende de ningún idioma. Coordenada sellada: Sutton Veny, Wiltshire, 15 de mayo de 2025.$rsv$,
     $rsv$Nested orbits around a lit center, a map of bodies in motion. The ratio between its radii falls on clean numbers, the mathematics that depends on no language. Sealed coordinate: Sutton Veny, Wiltshire, 15 May 2025.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2025/05/2.-Sutton-Veny-Wilts-15-05-25-OH2tif.jpg$rsv$, true, now()),
    ('dd1d8286-0b24-5608-880d-cfab8c79a0d0',
     $rsv$Wimborne$rsv$, $rsv$Wimborne, Dorset$rsv$, $rsv$Reino Unido$rsv$,
     50.8, -1.985, DATE '2025-04-11', 'grid',
     $rsv$Una retícula de nodos y celdas, un campo de señal ordenado como un idioma. Quien camina su centro reporta un cambio de frecuencia difícil de poner en palabras. Wimborne, Dorset guarda su huella desde el 11 de abril de 2025.$rsv$,
     $rsv$A lattice of nodes and cells, a signal field ordered like a language. Those who walk its center report a shift in frequency hard to put into words. Wimborne, Dorset has held its mark since 11 April 2025.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2025/04/Ben-Sasson_website-L.jpg$rsv$, true, now()),
    ('9e6d1e89-8480-5f05-a4e5-56711682c4a4',
     $rsv$Avebury$rsv$, $rsv$Avebury, Wiltshire$rsv$, $rsv$Reino Unido$rsv$,
     51.428, -1.854, DATE '2026-07-14', 'grid',
     $rsv$Una retícula de nodos y celdas, un campo de señal ordenado como un idioma. Su simetría es demasiado exacta para el azar y demasiado serena para el ruido. Detectado en Avebury, Wiltshire, 14 de julio de 2026, y aún resuena.$rsv$,
     $rsv$A lattice of nodes and cells, a signal field ordered like a language. Its symmetry is too exact for chance and too calm for noise. Detected at Avebury, Wiltshire, 14 July 2026, and it still resonates.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2026/07/Web-Ben-Sasson_final.jpg$rsv$, true, now()),
    ('91e28000-a58d-5492-97d4-25e0b97b33cd',
     $rsv$Milk Hill$rsv$, $rsv$Milk Hill, Wiltshire$rsv$, $rsv$Reino Unido$rsv$,
     51.372, -1.853, DATE '2026-07-12', 'grid',
     $rsv$Una retícula de nodos y celdas, un campo de señal ordenado como un idioma. Es un recordatorio de que el orden puede aparecer sin manos que lo tracen. El campo de Milk Hill, Wiltshire lo recibió el 12 de julio de 2026.$rsv$,
     $rsv$A lattice of nodes and cells, a signal field ordered like a language. It is a reminder that order can appear with no hands to trace it. The field at Milk Hill, Wiltshire received it on 12 July 2026.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2026/07/38.-Milk-Hill-Wilts-12-07-26-OH.jpg$rsv$, true, now()),
    ('8893bfec-2406-5be3-a6f0-4bc195cacc62',
     $rsv$Roundway$rsv$, $rsv$Roundway, Wiltshire$rsv$, $rsv$Reino Unido$rsv$,
     51.378, -1.975, DATE '2026-07-11', 'mandala',
     $rsv$Anillos concéntricos que se tejen hacia adentro, un mandala trazado en una sola pulsación. El patrón se siente antiguo y recién nacido al mismo tiempo. Registrado en Roundway, Wiltshire, 11 de julio de 2026.$rsv$,
     $rsv$Concentric rings weaving inward, a mandala traced in a single pulse. The pattern feels ancient and newborn at once. Recorded at Roundway, Wiltshire, 11 July 2026.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2026/07/33.-Roundway-Wilts-11-07-26-OH.jpg$rsv$, true, now()),
    ('5b1834fb-c3c6-57f8-8675-c7a2cb2ce320',
     $rsv$Tidcombe$rsv$, $rsv$Tidcombe, Wiltshire$rsv$, $rsv$Reino Unido$rsv$,
     51.32, -1.56, DATE '2026-07-07', 'spiral',
     $rsv$Un brazo en espiral que gira desde un núcleo brillante, la geometría del crecimiento hecha visible. Su silencio dice más que cualquier explicación. Se abrió sobre Tidcombe, Wiltshire el 7 de julio de 2026.$rsv$,
     $rsv$A spiral arm turning out from a bright core, the geometry of growth made visible. Its silence says more than any explanation. It opened over Tidcombe, Wiltshire on 7 July 2026.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2026/07/29.-Tidcombe-Wilts-07-07-26-OH2.jpg$rsv$, true, now()),
    ('1c2e5d40-1e93-5136-96f3-f6780fc9e045',
     $rsv$Zeal's Knoll (Mere)$rsv$, $rsv$Mere, Wiltshire$rsv$, $rsv$Reino Unido$rsv$,
     51.09, -2.27, DATE '2026-07-05', 'tri',
     $rsv$Tres brazos en simetría perfecta alrededor de un centro, la firma de lo ternario. La forma sostiene una tensión perfecta entre lo vacío y lo lleno. Coordenada sellada: Mere, Wiltshire, 5 de julio de 2026.$rsv$,
     $rsv$Three arms in perfect symmetry around a center, the signature of the threefold. The form holds a perfect tension between the empty and the full. Sealed coordinate: Mere, Wiltshire, 5 July 2026.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2026/07/23.-Mere-Wilts-05-07-26-OH2.jpg$rsv$, true, now()),
    ('5834a3fc-0955-5104-bf40-e60434ab7e6c',
     $rsv$Etchilhampton (2)$rsv$, $rsv$Etchilhampton, Wiltshire$rsv$, $rsv$Reino Unido$rsv$,
     51.339, -1.929, DATE '2026-07-04', 'tri',
     $rsv$Tres brazos en simetría perfecta alrededor de un centro, la firma de lo ternario. Late como una señal que espera ser reconocida, no descifrada. Etchilhampton, Wiltshire guarda su huella desde el 4 de julio de 2026.$rsv$,
     $rsv$Three arms in perfect symmetry around a center, the signature of the threefold. It pulses like a signal waiting to be recognized, not decoded. Etchilhampton, Wiltshire has held its mark since 4 July 2026.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2026/07/15.Etchilhampton-Wilts-04-07-26-OH.jpg$rsv$, true, now()),
    ('2d1bcaed-01ee-5b71-b0b4-8c936b35bfe4',
     $rsv$Alfred's Castle$rsv$, $rsv$Alfred's Castle, Oxfordshire$rsv$, $rsv$Reino Unido$rsv$,
     51.56, -1.59, DATE '2026-07-03', 'mandala',
     $rsv$Anillos concéntricos que se tejen hacia adentro, un mandala trazado en una sola pulsación. Es geometría que respira, no un dibujo que se queda quieto. Detectado en Alfred's Castle, Oxfordshire, 3 de julio de 2026, y aún resuena.$rsv$,
     $rsv$Concentric rings weaving inward, a mandala traced in a single pulse. It is geometry that breathes, not a drawing that stays still. Detected at Alfred's Castle, Oxfordshire, 3 July 2026, and it still resonates.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2026/07/9.-Bishopstone-Oxon-03-07-26-OH2.jpg$rsv$, true, now()),
    ('d1116a81-7b3a-559d-ab72-65e56cb56bb9',
     $rsv$Etchilhampton$rsv$, $rsv$Etchilhampton, Wiltshire$rsv$, $rsv$Reino Unido$rsv$,
     51.339, -1.929, DATE '2026-06-25', 'orbits',
     $rsv$Órbitas anidadas alrededor de un centro encendido, un mapa de cuerpos en movimiento. Marca un punto del campo donde la belleza se volvió tecnología de apertura. El campo de Etchilhampton, Wiltshire lo recibió el 25 de junio de 2026.$rsv$,
     $rsv$Nested orbits around a lit center, a map of bodies in motion. It marks a point in the field where beauty became a technology of opening. The field at Etchilhampton, Wiltshire received it on 25 June 2026.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2026/06/1.-Web-dji_fly_20260625_182336_0010_1782415559182_photo.jpg$rsv$, true, now()),
    ('1688eb35-9254-5145-8f34-d06fc7d4f660',
     $rsv$Zürcher Weinland$rsv$, $rsv$Zürcher Weinland, Suiza$rsv$, $rsv$Suiza$rsv$,
     47.6, 8.75, DATE '2026-06-23', 'web',
     $rsv$Una malla hexagonal de varias capas, la estructura misma del espacio dibujada sobre el campo. No entrega un mensaje para leer: entrega un estado para sentir. Registrado en Zürcher Weinland, Suiza, 23 de junio de 2026.$rsv$,
     $rsv$A many-layered hexagonal mesh, the structure of space itself drawn onto the field. It delivers no message to read: it delivers a state to feel. Recorded at Zürcher Weinland, Suiza, 23 June 2026.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2026/06/2.-BIRDVIEW_Kornkreis-4_1500px.jpg$rsv$, true, now()),
    ('b4372eba-6adf-576e-9525-6c6c15d84d17',
     $rsv$Kingweston (2)$rsv$, $rsv$Kingweston, Somerset$rsv$, $rsv$Reino Unido$rsv$,
     51.07, -2.68, DATE '2026-06-21', 'orbits',
     $rsv$Órbitas anidadas alrededor de un centro encendido, un mapa de cuerpos en movimiento. Apareció sin proceso visible, sobre un campo que horas antes estaba intacto. Se abrió sobre Kingweston, Somerset el 21 de junio de 2026.$rsv$,
     $rsv$Nested orbits around a lit center, a map of bodies in motion. It appeared with no visible process, over a field that hours earlier was untouched. It opened over Kingweston, Somerset on 21 June 2026.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2026/06/11.-_DSC1454-Kingsweston-Somerset-21-06-26-OH-1.jpg$rsv$, true, now()),
    ('131b2243-d27c-595f-b6f5-229c5a3f030c',
     $rsv$Great Wishford$rsv$, $rsv$Great Wishford, Wiltshire$rsv$, $rsv$Reino Unido$rsv$,
     51.12, -1.93, DATE '2026-06-15', 'tri',
     $rsv$Tres brazos en simetría perfecta alrededor de un centro, la firma de lo ternario. La proporción entre sus radios cae en números limpios, la matemática que no depende de ningún idioma. Coordenada sellada: Great Wishford, Wiltshire, 15 de junio de 2026.$rsv$,
     $rsv$Three arms in perfect symmetry around a center, the signature of the threefold. The ratio between its radii falls on clean numbers, the mathematics that depends on no language. Sealed coordinate: Great Wishford, Wiltshire, 15 June 2026.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2026/06/1.-Grovely-edited-15-06-26-OH.jpg$rsv$, true, now()),
    ('af43a9f9-dadc-5fec-8aef-f1554512d502',
     $rsv$Ditcheat$rsv$, $rsv$Ditcheat, Somerset$rsv$, $rsv$Reino Unido$rsv$,
     51.1, -2.52, DATE '2026-05-30', 'orbits',
     $rsv$Órbitas anidadas alrededor de un centro encendido, un mapa de cuerpos en movimiento. Quien camina su centro reporta un cambio de frecuencia difícil de poner en palabras. Ditcheat, Somerset guarda su huella desde el 30 de mayo de 2026.$rsv$,
     $rsv$Nested orbits around a lit center, a map of bodies in motion. Those who walk its center report a shift in frequency hard to put into words. Ditcheat, Somerset has held its mark since 30 May 2026.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2026/06/1.-Ditcheat-Somerset-31-05-26-Edited-.jpg$rsv$, true, now()),
    ('0e03db50-8f97-511b-842c-0765f6272c06',
     $rsv$White Sheet Hill$rsv$, $rsv$White Sheet Hill, Wiltshire$rsv$, $rsv$Reino Unido$rsv$,
     51.1, -2.23, DATE '2026-05-22', 'mandala',
     $rsv$Anillos concéntricos que se tejen hacia adentro, un mandala trazado en una sola pulsación. Su simetría es demasiado exacta para el azar y demasiado serena para el ruido. Detectado en White Sheet Hill, Wiltshire, 22 de mayo de 2026, y aún resuena.$rsv$,
     $rsv$Concentric rings weaving inward, a mandala traced in a single pulse. Its symmetry is too exact for chance and too calm for noise. Detected at White Sheet Hill, Wiltshire, 22 May 2026, and it still resonates.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2026/05/4.-White-Sheet-Hill-Wilts-22-05-26-OH.jpg$rsv$, true, now()),
    ('0db4336d-9afb-523f-97da-108748e91abf',
     $rsv$Kingweston$rsv$, $rsv$Kingweston, Somerset$rsv$, $rsv$Reino Unido$rsv$,
     51.07, -2.68, DATE '2026-05-10', 'grid',
     $rsv$Una retícula de nodos y celdas, un campo de señal ordenado como un idioma. Es un recordatorio de que el orden puede aparecer sin manos que lo tracen. El campo de Kingweston, Somerset lo recibió el 10 de mayo de 2026.$rsv$,
     $rsv$A lattice of nodes and cells, a signal field ordered like a language. It is a reminder that order can appear with no hands to trace it. The field at Kingweston, Somerset received it on 10 May 2026.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2026/05/1.-Kingsweston-10-05-26-TK.jpg$rsv$, true, now()),
    ('34ac3319-5bf5-5418-aaa9-75dc86d6b2f1',
     $rsv$Jack's Plantation$rsv$, $rsv$Jack's Plantation, Wiltshire$rsv$, $rsv$Reino Unido$rsv$,
     51.11, -2.32, DATE '2026-05-08', 'mandala',
     $rsv$Anillos concéntricos que se tejen hacia adentro, un mandala trazado en una sola pulsación. El patrón se siente antiguo y recién nacido al mismo tiempo. Registrado en Jack's Plantation, Wiltshire, 8 de mayo de 2026.$rsv$,
     $rsv$Concentric rings weaving inward, a mandala traced in a single pulse. The pattern feels ancient and newborn at once. Recorded at Jack's Plantation, Wiltshire, 8 May 2026.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2026/05/1-Alfreds-Tower-Wilts-08-05-26.jpg$rsv$, true, now()),
    ('867b8889-ef68-5b60-8a12-775fb4896a4d',
     $rsv$Waden Hill$rsv$, $rsv$Waden Hill, Wiltshire$rsv$, $rsv$Reino Unido$rsv$,
     51.42, -1.85, DATE '2026-04-29', 'spiral',
     $rsv$Un brazo en espiral que gira desde un núcleo brillante, la geometría del crecimiento hecha visible. Su silencio dice más que cualquier explicación. Se abrió sobre Waden Hill, Wiltshire el 29 de abril de 2026.$rsv$,
     $rsv$A spiral arm turning out from a bright core, the geometry of growth made visible. Its silence says more than any explanation. It opened over Waden Hill, Wiltshire on 29 April 2026.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2026/05/1.-Waden-Hill-Avebury-Wilts-29-04-26-OSR.jpg$rsv$, true, now()),
    ('dc9a1eb1-d309-54e6-aaeb-6dc578dd279c',
     $rsv$Ilchester$rsv$, $rsv$Ilchester, Somerset$rsv$, $rsv$Reino Unido$rsv$,
     51.005, -2.68, DATE '2026-04-04', 'mandala',
     $rsv$Anillos concéntricos que se tejen hacia adentro, un mandala trazado en una sola pulsación. La forma sostiene una tensión perfecta entre lo vacío y lo lleno. Coordenada sellada: Ilchester, Somerset, 4 de abril de 2026.$rsv$,
     $rsv$Concentric rings weaving inward, a mandala traced in a single pulse. The form holds a perfect tension between the empty and the full. Sealed coordinate: Ilchester, Somerset, 4 April 2026.$rsv$,
     $rsv$https://temporarytemples.co.uk/wp-content/uploads/2026/04/2.-Bondip-Hill-nr-Ilchester-Somerset-04-04-2026-L.jpg$rsv$, true, now())
ON CONFLICT (id) DO NOTHING;
